### ISSUE TITLE
error in return this.source().length . Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by laukaichung** [sysgears/persistgraphql-webpack-plugin#19]
Does it work with "webpack": "^3.10.0" and "webpack-merge": "^4.1.1"?

I follow the ` front-end only` example but get this error:

````
/home/project/node_modules/webpack-sources/lib/Source.js:17
                return this.source().length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at RawSource.size (/home/project/node_modules/webpack-sources/lib/Source.js:17:23)
    at obj.assets.compilationAssets.map.asset (/home/project/node_modules/webpack/lib/Stats.js:271:38)
    at Array.map (<anonymous>)
    at Stats.toJson (/home/project/node_modules/webpack/lib/Stats.js:268:35)
    at Compiler.<anonymous> (/home/project/node_modules/html-webpack-plugin/index.js:68:44)
    at Compiler.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:206:13)
    at Compiler.emitAssets (/home/project/node_modules/webpack/lib/Compiler.js:354:8)
    at onCompiled (/home/project/node_modules/webpack/lib/Compiler.js:240:9)
    at applyPluginsAsync.err (/home/project/node_modules/webpack/lib/Compiler.js:510:14)
    at next (/home/project/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.<anonymous> (/home/project/node_modules/webpack/lib/CachePlugin.js:78:5)
    at next (/home/project/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/home/project/node_modules/persistgraphql-webpack-plugin/index.js:156:7)
    at Compiler.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:206:13)
    at compilation.seal.err (/home/project/node_modules/webpack/lib/Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/home/project/node_modules/webpack/lib/Compilation.js:680:19)
    at Compilation.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/home/project/node_modules/webpack/lib/Compilation.js:671:11)
    at Compilation.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:195:46)
    at self.applyPluginsAsync.err (/home/project/node_modules/webpack/lib/Compilation.js:666:10)
    at Compilation.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:195:46)
    at sealPart2 (/home/project/node_modules/webpack/lib/Compilation.js:662:9)
    at Compilation.applyPluginsAsyncSeries (/home/project/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/home/project/node_modules/webpack/lib/Compilation.js:605:8)
    at applyPluginsParallel.err (/home/project/node_modules/webpack/lib/Compiler.js:504:17)
    at /home/project/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/project/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/project/node_modules/webpack/lib/Compilation.js:477:14)
    at process._tickCallback (internal/process/next_tick.js:176:11)
````

I'm using a few other plugins but removing them still gets that error.
I find that removing `filename` from the option would prevent the error, but there's no 'persisted_queries.json' output after webpack finishes compiling. 

````
module.exports = {
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        use: 'graphql-tag/loader'
      },
    ]
  }

  plugins: [
    new webpack.optimize.CommonsChunkPlugin(),
    new HtmlWebpackPlugin(),
    new webpack.DefinePlugin(),
    new ServiceWorkerWebpackPlugin(),
    new PersistGraphQLPlugin({filename: 'persisted_queries.json',
        moduleName: path.resolve('node_modules/persisted_queries.json')})
  ]
};
````

Would it be caused by this part in the persistgraphql-webpack-plugin/index.js?

````
  if (self.options.filename) {
    compiler.plugin('after-compile', function(compilation, callback) {
      if (!compilation.compiler.parentCompilation) {
        compilation.assets[self.options.filename] = new RawSource(self._queryMap);
      }
      callback();
    });
  }
````

**Comment by larixer** [comment]
@stonecold123 I'm not sure how can I figure out something from this information. Please either try to find the cause of the issue yourself and provide details or please provide example project on GitHub that reproduces this issue.
